### ISSUE TITLE
New alternative pseudo-icon

### ISSUE THREAD

**Issue by arieldelfor** [natgeo/icongs#5]
Hi!

At yourshot we are requiring of some icons that i couldn't found here but are very similar. I'd like to contribute and add some alternatives.
It would great if i could add some thing like next:
![icongs-facebook--bg-blue](https://s3.amazonaws.com/uploads.hipchat.com/43415/413332/oIaAXRiXPQi7vkO/facebook--bg-blue.png)

My idea is to add some modifier BEM style like --bg-blue... so that if the user makes use of it would be
 .icongs .icongs-facebook .icongs-facebook--bg-blue or whatever you prefer.

scss approach:
```SCSS
.icongs-facebook--bg-blue {
  background-color: #1E71B7;
  border-radius: 3px;
  color: white;
  &:before {
    left: .1em;
    position: relative;
    top: .1em;
 }
}
```

Also i need a change for Pinterest where it has an orage circle as background.

Jira Reference: https://jira.nationalgeographic.com/secure/attachment/64699/gallery-share-icons.png
